---
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
  labels:
    name: adguard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 80
    beta_bind_port: 0
    users:
    - name: admin
      password: $2a$10$VQc2F7zm5dLdC2.6713AveHlw4CUuhkjZWJhtqyrq8xv3YR2/drBC
    auth_attempts: 5
    block_auth_min: 15
    http_proxy: ""
    language: ""
    rlimit_nofile: 0
    debug_pprof: false
    web_session_ttl: 720
    dns:
      bind_hosts:
      - 0.0.0.0
      port: 53
      statistics_interval: 1
      querylog_enabled: true
      querylog_file_enabled: true
      querylog_interval: 90
      querylog_size_memory: 1000
      anonymize_client_ip: false
      protection_enabled: true
      blocking_mode: default
      blocking_ipv4: ""
      blocking_ipv6: ""
      blocked_response_ttl: 10
      parental_block_host: family-block.dns.adguard.com
      safebrowsing_block_host: standard-block.dns.adguard.com
      ratelimit: 20
      ratelimit_whitelist: []
      refuse_any: true
      upstream_dns:
      - 10.43.31.2 # lancache.lancache.svc.cluster.local # (if not using lancahe this and use the unbound entry below instead)
      # - 10.43.31.1 # unbound.unbound.svc.cluster.local
      upstream_dns_file: ""
      bootstrap_dns:
      - 9.9.9.10
      - 149.112.112.10
      - 2620:fe::10
      - 2620:fe::fe:10
      all_servers: false
      fastest_addr: false
      allowed_clients: []
      disallowed_clients: []
      blocked_hosts:
      - version.bind
      - id.server
      - hostname.bind
      cache_size: 4194304
      cache_ttl_min: 0
      cache_ttl_max: 0
      bogus_nxdomain: []
      aaaa_disabled: false
      enable_dnssec: false
      edns_client_subnet: false
      max_goroutines: 300
      ipset: []
      filtering_enabled: true
      filters_update_interval: 24
      parental_enabled: false
      safesearch_enabled: false
      safebrowsing_enabled: false
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      parental_cache_size: 1048576
      cache_time: 30
      rewrites:
      - domain: unraid
        answer: 192.168.1.110
      - domain: '*.unraid.lan'
        answer: 192.168.1.110
      - domain: unraid.lan
        answer: 192.168.1.110
      - domain: '*.jovian.lan'
        answer: 192.168.1.99
      blocked_services: []
      local_domain_name: local
      resolve_clients: true
      local_ptr_upstreams:
      - kube-dns.kube-system.svc.cluster.local # k3s resolver
      - 192.168.1.1 # local network dns
    tls:
      enabled: false
      server_name: ""
      force_https: false
      port_https: 443
      port_dns_over_tls: 853
      port_dns_over_quic: 784
      port_dnscrypt: 0
      dnscrypt_config_file: ""
      allow_unencrypted_doh: false
      strict_sni_check: false
      certificate_chain: ""
      private_key: ""
      certificate_path: ""
      private_key_path: ""
    filters:
    - enabled: true
      url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      name: AdGuard DNS filter
      id: 1
    - enabled: false
      url: https://adaway.org/hosts.txt
      name: AdAway Default Blocklist
      id: 2
    - enabled: true
      url: https://www.malwaredomainlist.com/hostslist/hosts.txt
      name: MalwareDomainList.com Hosts List
      id: 4
    - enabled: true
      url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      name: WindowsSpyBlocker - Hosts spy rules
      id: 1639209484
    - enabled: true
      url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
      name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
      id: 1639209485
    - enabled: true
      url: https://hblock.molinero.dev/hosts_adblock.txt
      name: hBlock Ads
      id: 1639209486
    whitelist_filters: []
    user_rules: []
    dhcp:
      enabled: false
      interface_name: ""
      dhcpv4:
        gateway_ip: ""
        subnet_mask: ""
        range_start: ""
        range_end: ""
        lease_duration: 86400
        icmp_timeout_msec: 1000
        options: []
      dhcpv6:
        range_start: ""
        lease_duration: 86400
        ra_slaac_only: false
        ra_allow_slaac: false
    clients: []
    log_compress: false
    log_localtime: false
    log_max_backups: 0
    log_max_size: 100
    log_max_age: 3
    log_file: ""
    verbose: false
    schema_version: 10
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: adguard
  labels:
    app: adguard-home
spec:
  ports:
    - port: 80
      name: web
      targetPort: 80  # needs to be 3000 for initial setup
    - port: 53
      name: dns
    - port: 53
      name: dns-udp
      protocol: UDP
  selector:
    app: adguard-home
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adguard-home
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  selector:
    matchLabels:
      app: adguard-home
  serviceName: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      terminationGracePeriodSeconds: 1800
      initContainers:
        - name: copy
          image: busybox:1.28
          command: ["/bin/sh", "-c", "cp -f /config/AdGuardHome.yaml /opt/adguardhome/conf/"]
          volumeMounts:
            - name: tmp-conf
              mountPath: /config
            - name: conf
              mountPath: /opt/adguardhome/conf
      containers:
        - name: adguard-home
          image: adguard/adguardhome
          ports:
            - containerPort: 80
              name: web
            - containerPort: 53
              name: dns
            - containerPort: 53
              name: dns-udp
              protocol: UDP
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: conf
              mountPath: /opt/adguardhome/conf
            - name: work
              mountPath: /opt/adguardhome/work
      volumes:
        - name: tmp-conf
          configMap:
            name: adguard-config
            items:
              - key: AdGuardHome.yaml
                path: AdGuardHome.yaml
  volumeClaimTemplates:
    - metadata:
        name: conf
        namespace: adguard
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: nfs-local
        resources:
          requests:
            storage: 50Mi
    - metadata:
        name: work
        namespace: adguard
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: nfs-local
        resources:
          requests:
            storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-home
  namespace: adguard
spec:
  defaultBackend:
    service:
      name: adguard-home
      port:
        number: 80
  rules:
    - host: "adguard.jovian.lan"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: adguard-home
                port:
                  number: 80
---
# Host binding udp-dns
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-udp
  namespace: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-dns"
spec:
  type: LoadBalancer
  selector:
    app: adguard-home
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.95
---
# Host binding tcp-dns
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-tcp
  namespace: adguard
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-dns"
spec:
  type: LoadBalancer
  selector:
    app: adguard-home
  ports:
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.95
