apiVersion: v1
kind: Namespace
metadata:
  name: adguard
  labels:
    name: adguard
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: adguard
  labels:
    app: adguard-home
spec:
  ports:
  - port: 80
    name: web
    targetPort: 80 # needs to be 3000 for initial setup
  - port: 53
    name: dns
  - port: 53
    name: dns-udp
    protocol: UDP
  selector:
    app: adguard-home
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adguard-home
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  selector:
    matchLabels:
      app: adguard-home
  serviceName: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome
        ports:
        - containerPort: 80
          name: web
        - containerPort: 53
          name: dns
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: conf
          mountPath: /opt/adguardhome/conf
        - name: work
          mountPath: /opt/adguardhome/work
  volumeClaimTemplates:
  - metadata:
      name: conf
      namespace: adguard
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: nfs-local
      resources:
        requests:
          storage: 50Mi
  - metadata:
      name: work
      namespace: adguard
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: nfs-local
      resources:
        requests:
          storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-home
  namespace: adguard
spec:
  defaultBackend:
    service:
      name: adguard-home
      port:
        number: 80
  rules:
  - host: "adguard.jovian.lan"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: adguard-home
            port:
              number: 80
---
# Host binding udp-dns
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-udp
  namespace: adguard
spec:
  type: LoadBalancer
  selector:
    app: adguard-home
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
  externalTrafficPolicy: Local
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.90
---
# Host binding tcp-dns
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-tcp
  namespace: adguard
spec:
  type: LoadBalancer
  selector:
    app: adguard-home
  ports:
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  externalTrafficPolicy: Local
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.90