# helm repo add metallb https://metallb.github.io/metallb
# helm install metallb metallb/metallb -f values.yaml -n metallb-system
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
      - 192.168.1.95-192.168.1.99